### ISSUE TITLE
Task 'uploadPgyer' not found in root project 'xxx'.

### ISSUE THREAD

**Issue by rikyou** [dodocat/pgyer#1]
执行命令./gradlew uploadPgyer出现这个错误Task 'uploadPgyer' not found in root project 'xxx'.
是不是我哪里用的不对

**Comment by dodocat** [comment]
你把你的 `build.gradle` 文件放上来看看, 包括 top level 和模块下的.

**Comment by rikyou** [comment]
工程下面的build.gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'org.quanqi:pgyer:2.0'

```
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}

apply plugin: 'org.quanqi.pgyer'

pgyer {
    _api_key = "456f9e64bfe06f7eacaac558c23cf4e9"
    uKey = "e911e01d960e69fc6887e5fc9f625f2f"
}

apks {
    release {
        sourceFile = file("/Users/rikyou")
    }
}
```

}

allprojects {
    repositories {
        jcenter()
        maven { url "https://raw.githubusercontent.com/Pgyer/mvn_repo_pgyer/master" }
    }
}
app model下得build.gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

```
defaultConfig {
    applicationId "com.pgyer.pgyersdk.test"
    minSdkVersion 9
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.pgyersdk:sdk:2.1.0'
}

我不太熟悉怎么用你的东西，是不是我得引用你的工程，还是你这个是远程仓库的一个库，类似远程aar的库？

**Comment by dodocat** [comment]
你的配置至少有这些错误

 `classpath 'org.quanqi:pgyer:2.0'` 这里的版本错了 当前的版本是 `0.1.0`

```
dependencies {
compile 'com.android.support:appcompat-v7:21.0.3'
compile 'com.pgyersdk:sdk:2.1.0'
}
```

`compile 'com.pgyersdk:sdk:2.1.0'` 这一行完全是多余的

```
apks {
    release {
        sourceFile = file("/Users/rikyou")
    }
}
```

这里的路径是要上传的 apk 文件的路径.

你需要学习一下 gradle 的基础知识. https://developer.android.com/tools/building/plugin-for-gradle.html

**Comment by kunnzhou001** [comment]
buildscript {
    repositories {
        jcenter()
    }

```
tasks.withType(Compile) {
    options.encoding = "UTF-8"
}

dependencies {
    classpath 'com.android.tools.build:gradle:2.1+'
    classpath 'org.quanqi:pgyer:0.1.2'
}
```

}

apply plugin: 'org.quanqi.pgyer'
//声明仓库的源，这里可以看到是指明的jcenter(), 之前版本则是mavenCentral()
//jcenter可以理解成是一个新的中央远程仓库，兼容maven中心仓库，而且性能更优
allprojects {
    repositories {
        jcenter()
    }
}

pgyer {
    _api_key = ""
    uKey = ""
}

 if(gradle.UPDATE_TO_PGY){
        if('prd'.equalsIgnoreCase(build_env)){
            pgyer._api_key = ''
            pgyer.uKey = ''
            println  "上传生产环境PGY _api_key="+pgyer._api_key+";uKey="+pgyer.uKey
        }else{
            pgyer._api_key = ''
            pgyer.uKey = ''
            println  "上传测试环境PGY _api_key="+pgyer._api_key+";uKey="+pgyer.uKey
        }
        apks {
            release{
                sourceFile = file(gradle.APK_BACKUP_PATH)
            }
        }
    }

Execute Windows batch command in Jenkins

$ ./gradlew uploadPgyer、

FATAL: command execution failed
java.io.IOException: Cannot run program "cmd" (in directory "/data/jenkins/workspace/Loan-Android"): error=2, 没有那个文件或目录

麻烦帮我看看，这个错误
